name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@master
      - name: cmake build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: execute ctest
        run: |
          cd build
          ctest
