name: cpp-build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@master
      - name: cmake build
        run: |
          mkdir build
          cd build
          cmake ..
          make
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: check version
        run: |
          bash --version
          echo ""
          clang-format --version
      - name: checkout branch
        uses: actions/checkout@master
      - name: clang-check
        run: |
          ./scripts/formatting.sh src include test
