name: python-build

on: push

jobs:
  pylint-check:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout branch
        uses: actions/checkout@master
      - name: setup linter
        run: pip3 install pylint
      - name: linter check
        run: pylint src/test_actions
  pycodestyle-check:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout branch
        uses: actions/checkout@master
      - name: setup linter
        run: pip3 install pycodestyle
      - name: linter check
        run: pycodestyle src/test_actions
